from alpine:3.21.3

run apk add \
    texlive-full \
    texmf-dist-latexrecommended \
    texmf-dist-latexextra \
    texmf-dist-binextra \
    biblatex \
    texmf-dist-bibtexextra \
    make \
    git \
    git-lfs \
    cmake \
    g++ \
    g++-arm-none-eabi 