name: "Build"

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Build docker images
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          push: false
          tags: local
      - name: Build presentation
        run: docker run -v $PWD:/srv -w/srv local sh -c "cd presentation && mkdir build && cd build && cmake .. && make"
      - name: Build examples
        run: docker run -v $PWD:/srv -w/srv local sh -c "cd examples && mkdir build && cd build && cmake .. && make"
